### ISSUE TITLE
muti-photo upload

### ISSUE THREAD

**Issue by williamluoweizhen** [pavelosipov/POSInputStreamLibrary#8]
Hi, Pavel Osipov,can I use POSInputStreamLibrary with AFnetworking to upload muti-photos instead of one photo?

**Comment by pavelosipov** [comment]
Good day @williamluoweizhen. @bancek, can your answer the question about AFNetworking integration?

**Comment by bancek** [comment]
Multiple photos are supported.

Example:
https://github.com/bancek/POSInputStreamAFNetworkingExample/blob/master/POSInputStreamAFNetworkingExample/ViewController.m#L81

**Comment by williamluoweizhen** [comment]
@bancek  Thank you for reply. And another question, I want to know that, after I upload the photo to a server, and how can I analyze the post request ,get the photo and store to the database? I need the process for parsing the formData.

**Comment by bancek** [comment]
AFNetworking uses multipart upload:

http://stackoverflow.com/questions/16958448/what-is-http-multipart-request

If you are using PHP you should check this link out:

http://www.w3schools.com/php/php_file_upload.asp

**Comment by williamluoweizhen** [comment]
@pavelosipov  @bancek  thanks a lot！

**Comment by williamluoweizhen** [comment]
@bancek  my server's code is that 
`        public String uploadMedicalExaminationReport(String username, String examDate, String hospital, String description, MultipartHttpServletRequest request) throws IOException {
        Map<String, MultipartFile> fileMap = request.getFileMap();
        System.out.println(fileMap.size());
        Set<String> keySet = fileMap.keySet();
        for (String temp : keySet) {
            MultipartFile multipartFile = fileMap.get(temp);
            String newfilename = username + "_" + new Date().getTime() + "_" + multipartFile.getOriginalFilename();
            String PathAndName = filePath + newfilename;
            String saveUrl = savePath + newfilename;
            File resultFile = new File(PathAndName);
            try {
                multipartFile.transferTo(resultFile);
            } catch (IllegalStateException | IOException e) {
                e.printStackTrace();
                return "fail";
            }
            filePathList += (saveUrl + ";"); //多个文件的路径之间用分号隔开
        }
｝
and the app's code :
- (void) uploadAsset:(ALAsset_)asset andAnother:(ALAsset_)anotherAsset toUrl:(NSString_)url progressBlock:(void (^)(long long bytesWriten, long long bytesTotal))progressBlock success:(void (^)(id responseObject))success failure:(void (^)(NSError_ error))failure
  {
  NSDictionary *parameter = @{@"username":@"user1",@"examDate":@"2011-1-1",@"hospital":@"lwz",@"description":@"======="};
  
  AFHTTPRequestOperationManager *manager = [AFHTTPRequestOperationManager manager];
  
  AFHTTPRequestOperation *op = [manager POST:url parameters:parameter constructingBodyWithBlock:^(id<AFMultipartFormData>  _Nonnull formData) {
      [self formData:formData appendAsset:asset fieldName:@"file1"];
      [self formData:formData appendAsset:anotherAsset fieldName:@"file2"];
  } success:^(AFHTTPRequestOperation \* _Nonnull operation, id  _Nonnull responseObject) {
      success(responseObject);
  } failure:^(AFHTTPRequestOperation \* _Nonnull operation, NSError \* _Nonnull error) {
      failure(error);
  }];
  
  [op setUploadProgressBlock:^(NSUInteger bytesWritten, long long totalBytesWritten, long long totalBytesExpectedToWrite) {
      progressBlock(totalBytesWritten, totalBytesExpectedToWrite);
  }];
  }

almost the same to your code, but it can only upload one picture，it can't support Multiple photos. How to solve the problem if I dont't want to edit the server's code?

**Comment by bancek** [comment]
Server's code seems to support multiple files. App's code should upload two photos otherwise there would be an nil exception in the application.
